### ISSUE TITLE
Error in the console during first installation

### ISSUE THREAD

**Issue by sonytruelove** [Kkordik/GOnews#1]
![изображение](https://github.com/user-attachments/assets/799ce2fc-1779-4720-b310-9fc93136ffa0)
```FileNotFoundError: [Errno 2] No such file or directory: 'configuration.yaml'```

**Comment by sonytruelove** [comment]
It's happen after `python main.py` command

**Comment by Kkordik** [comment]
Yes, I forgot to upload it on github. Now should work
